# Generated by Django 2.2.5 on 2019-10-25 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airports',
            fields=[
                ('id_airport', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='pk_airport')),
                ('codigo', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='vuelos',
            fields=[
                ('id_vuelos', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='pk_vuelo')),
                ('duration', models.IntegerField(null=True)),
                ('id_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_destino', to='vuelos.airports')),
                ('id_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_origen', to='vuelos.airports')),
            ],
        ),
        migrations.CreateModel(
            name='pasajeros',
            fields=[
                ('id_pasajero', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='pk_pasajero')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('vuelos', models.ManyToManyField(blank=True, related_name='pasajerosq', to='vuelos.vuelos')),
            ],
        ),
    ]
