# Generated by Django 2.2.5 on 2019-10-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airports',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
